compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.10.3.cjs
